### ISSUE TITLE
Can you Integrate OpenAI Whisper for Audio Transcription?

### ISSUE THREAD

**Issue by KitteeRusty** [PStarH/LLM-boost-recognition#2]
Maybe you can enhance OCR.py by integrating OpenAI's Whisper model to allow transcription of audio files alongside OCR processing. This will enable the script to handle documents with embedded audio components. Or you can try to use NLP to do sentimental analysis

**Comment by PStarH** [comment]
I don't want to use sentimental analysis because it is quite redundant, I only wanted to make the OCR and Voice Recognition more accurate in this project. The Whisper model is already implemented with the newest update

**Comment by KitteeRusty** [comment]
thank you
